### ISSUE TITLE
消息推送的问题

### ISSUE THREAD

**Issue by SpaceVector** [QXAzusa/tencent-push#4]
为什么我只能收到白名单的群的推送，收不到正常的QQ消息推送啊

**Comment by QXAzusa** [comment]
是用MiPush或FCM推送的吗？如果是的话我刚刚修了。
[Debug - 私聊消息变量错误](https://github.com/QXAzusa/tencent-push/commit/5c1d7d653ac04430e5110acd8ed08895cd5aa824)

**Comment by SpaceVector** [comment]
对，用的mipush，麻烦了
